### ISSUE TITLE
In tests, kfun cannot be found

### ISSUE THREAD

**Issue by victorminden** [klho/FLAM#2]
I get an "Undefined function or variable 'Kfun'." because Kfun in many/all the tests seems to now live one scope higher than it used to?  Maybe this is a version-specific thing, but I see:

` % kernel function
  function K = Kfun(x,y)
    dx = bsxfun(@minus,x(1,:)',y(1,:));
    dy = bsxfun(@minus,x(2,:)',y(2,:));
    dz = bsxfun(@minus,x(3,:)',y(3,:));
    K = 1/(4*pi)./sqrt(dx.^2 + dy.^2 + dz.^2);
  end
end`

Where that last end closes the top-level function.  Then, Afun2 etc. live outside the top-level function.

**Comment by klho** [comment]
I must have broken this in trying to make everything Octave-compatible also. Unfortunately, I don't have access to MATLAB to test anymore. Could you try pulling out Kfun into the top-level scope and seeing if that works? It looks to just be different MATLAB vs. Octave behavior in handling nested function visibility.

**Comment by victorminden** [comment]
Yes that seems to fix it locally, should have mentioned.  If that doesn't break Octave compatibility seems like that's the fix.

**Comment by klho** [comment]
Hopefully should be fixed now.
