### ISSUE TITLE
What is the input X in HIFDE2X?

### ISSUE THREAD

**Issue by wangguoguo-cpu** [klho/FLAM#6]
Excuse me, I wonder what is the input X in HIFDE2X? For a 2 dimension problem with coefficient A of N*N, is X a random matrix of 2*N? If not, then what is the input X ? Is there any papers for me to find some information about it? Looking forward to your answers, thank you very much!

**Comment by klho** [comment]
The input X denotes the spatial coordinates attached to each matrix index. This is for the purpose of using the spatial geometry to inform which matrix blocks are low-rank; please see the README. For examples, see, e.g., hifde2/test/fd_square1x.m, where the points X just describe a regular grid on the unit square. (Note that the algorithm can technically be implemented in a fully algebraic way using graph partitioners, etc. but we have not done that here.)

**Comment by wangguoguo-cpu** [comment]
Thank you for your patient answers, from which I unsderstand the relationship between the input X and the coresponding coefficient matrix.
     By the way, when I test 'fd_square1x' or 'fd_square4x', it occurs another two questions.  
    The first one is about building tree. In 92th of HYPOCT as ''idx = ldiv.*(x(:,xi) > ctr)'' , it warns that ''The matrix dimensions must be consistent'', from which  I find that ctr is $d*1$ but x(:,xi) is $d*n$, so, is there any input errors for me?
    The second one is about 'skip'. From HIFDE2X or HIFDE3X, I know that SKIP(D) sets the skip setting for skeletonization in dimension D (faces for D = 2 and edges for D = 1). And in fd_square1x and fd_square4x, I see you choose 'skip=2'. However, as README shows, HIFDE2 does reduce 2D problems (squares) to 1D (edges) to 0D (points), so I wonder why do you set 'skip' to skip the Skeletonization step? Besides, If I choose the default 'skip=0' in HIFDE2X or HIFDE3X, it may warn that  ''The matrix dimensions must be consistent'' in skeletonization step with 'off = [0 -1; -1 0; 0 1; 1 0]'  and 'ctr(:,idx) = t.nodes(i).ctr + 0.5*l.*off.' Is there any explanations for this phenomenon?
    Above questions confuse me for a long time, and I did't find any bugs in these codes so far by now. Of course maybe I didn’t understand these codes thoroughly even though I have read related articles in your list. Anyway, looking forward to your answers.

**Comment by klho** [comment]
1. For the "matrix dimensions must be consistent" warnings -- I recall these being emitted in older versions of MATLAB, before broadcasting was more natively supported (see https://blogs.mathworks.com/loren/2016/10/24/matlab-arithmetic-expands-in-r2016b/). Newer versions handle these without complaint. For older versions, you can either suppress the warnings or rewrite those lines using `bsxfun`, etc. The computations should be correct in any case.

2. For `hifde2x`, `skip` is a scalar input indicating how many initial skeletonization levels to skip. For example, in `fd_square1x`, `skip = 2` means to skip skeletonization on the first two levels. This is different from the behavior for `hifde3x`, where `skip` is a vector to allow control of the above type over multiple kinds (face/edge) of skeletonization. Note the difference between `skip = 2` and `skip(2)`.

**Comment by wangguoguo-cpu** [comment]
OK, thank you for your patient answers!
